---
name: Tests
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14.15
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
        - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.5.3
          gemfile: Gemfile.cucumber-1.3
          bundler: 1.17.3
        - ruby: 2.5.3
          gemfile: Gemfile.cucumber-2.4
          bundler: 1.17.3
        - ruby: 2.5.3
          gemfile: Gemfile.cucumber-3.0
          bundler: 1.17.3
        - ruby: 2.5.3
          gemfile: Gemfile.cucumber-3.1
          bundler: 1.17.3

        - ruby: 2.6.6
          gemfile: Gemfile.cucumber-4.1
          bundler: 2.4.22

        - ruby: 2.7.2
          gemfile: Gemfile.cucumber-5.3
          bundler: 2.4.22

        - ruby: 3.2.0
          gemfile: Gemfile.cucumber-4.1
          bundler: 2.4.22
        - ruby: 3.2.0
          gemfile: Gemfile.cucumber-5.3
          bundler: 2.4.22
        - ruby: 3.2.0
          gemfile: Gemfile.rails-7
          bundler: 2.6.3
        - ruby: 3.2.0
          gemfile: Gemfile.rails-8
          bundler: 2.6.3
        - ruby: 3.4.1
          gemfile: Gemfile.rails-7
          bundler: 2.6.3
        - ruby: 3.4.1
          gemfile: Gemfile.rails-8
          bundler: 2.6.3

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Setup database
      run: |
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -c 'create database cucumber_factory_test;' -U postgres -p 5432 -h localhost
    - name: Bundle
      run: |
        gem install bundler:${{ matrix.bundler }}
        bundle _${{ matrix.bundler }}_ install --no-deployment
    - name: Run tests
      run: bundle _${{ matrix.bundler }}_ exec rspec
